language: java
jdk:
  - openjdk11
cache:
  directories:
    - $HOME/.m2
install:
  - gd_url=https://github.com/mozilla/geckodriver/releases/download
  - gd_ver=v0.27.0
  - ( mkdir -pv bin; cd bin ; curl -L "${gd_url}/${gd_ver}/geckodriver-${gd_ver}-linux64.tar.gz" | gunzip | tar xf - ; chmod +x geckodriver )
  - mvn -B -V dependency:resolve
before_script:
  - export PATH="$PATH:$HOME/bin"
  - echo "$PATH"
script:
  - mvn -B -DskipTests=false -Dmaven.javadoc.skip=true -Dtest.drivers=htmlunit,phantomjs test
sudo: required
