language: java
jdk:
  - oraclejdk7
  - oraclejdk8
  - openjdk7
before_install:
  - date +"[%Y-%m-%d %H:%M:%S] before_install"
  - echo "installing PhantomJS 1.9.2"
  - wget http://phantomjs.googlecode.com/files/phantomjs-1.9.2-linux-x86_64.tar.bz2
  - tar xvf phantomjs-1.9.2-linux-x86_64.tar.bz2
  - mkdir bin
  - sudo mv phantomjs-1.9.2-linux-x86_64/bin/phantomjs bin/phantomjs
  - bin/phantomjs --version
  - export PATH="bin:$PATH"
  - ls -la bin/phantomjs
before_script:
  - "phantomjs --version"
install: /bin/true
script: mvn -U -DskipTests=false -Dtest.drivers=htmlunit,phantomjs clean test
